export interface aminoacido {
    acido_aspartico: number,
    treonina: number,
    serina: number,
    acido_glutaminico: number,
    prolina: number,
    glicina: number,
    alanina: number,
    cisteina: number,
    valina: number,
    metionina: number,
    isoleucina: number,
    leucina: number,
    tirosina: number,
    fenilalanina: number,
    histidina: number,
    lisina: number,
    arginina: number,
    triptofano: number,
    cod_alimento: number
}